---
- name: install openstack-nova packets
  yum: "name=openstack-nova-compute state=latest"
- name: replace nova.conf for compute node
  template: "src=compute-nova.conf.j2  dest=/etc/nova/nova.conf owner=nova group=nova mode=644"
  notify: restart openstack-nova-compute.service
#- name: Discover compute hosts
#  shell: su -s /bin/sh -c "nova-manage cell_v2 discover_hosts --verbose" nova
