- include: neutron_mysql_user.yml
  when: inventory_hostname in groups['controller']
  tags: neutron_mysql

- include: neutron_base.yml
  when: inventory_hostname in groups['controller']
  tags: neutron_base

- include: controller/main.yml
  when: inventory_hostname in groups['controller']
  tags: neutron-controller

