- name: ensure neutron database is present
  mysql_db: name=neutron state=present
- name: ensure neutron database user is present
  mysql_user: name=neutron host={{ item }} password={{ neutron_mysql_password }}  priv=neutron.*:ALL
  with_items:
    - "%"
    - "localhost"
    - "controller"
