---
- name: Create the nova user
  os_user:
    state: present
    domain: default
    name: nova
    password: "{{ nova_user_pass  }}"
    update_password: on_create
    default_project: admin
  tags: test_nova
- name: add nova to admin role
  os_user_role:
    user: nova
    role: admin
    project: service
#  shell: source /root/admin-openrc; openstack role add --project service --user glance admin
#  when: inventory_hostname == run_shade_node
#  keystone_user:
#    login_user: admin
#    login_password: admin
#    role: admin 
#    user: john 
#    tenant: demo
#  os_user:
#    auth: '{{ auth_dict }}'
#    state: present
#    name: glance
#    password: glance
#    domain: default
#    default_project: glance
#    enabled: True
#  when: inventory_hostname == run_shade_node
- name: create the nova service
  os_keystone_service:
    state: present
    name: nova
    service_type: compute
    description: OpenStack Compute
- name: Create the nova  service API endpoints
  os_keystone_service_endpoint:
    state: present
    service: "nova"
    interface: "public"
    url: "http://controller:8774/v2.1/%(tenant_id)s" 
    region: "RegionOne"
  tags: test_endpoint
- name: internal url
  os_keystone_service_endpoint:
    state: present
    service: "nova"
    interface: "internal"
    url: "http://controller:8774/v2.1/%(tenant_id)s"
    region: "RegionOne"
- name: admin url
  os_keystone_service_endpoint:
    state: present
    service: "nova"
    interface: "admin"
    url: "http://controller:8774/v2.1/%(tenant_id)s"
    region: "RegionOne"
### placement
- name: Create a Placement service user
  os_user:
    state: present
    domain: default
    name: placement
    password: "{{ placement_pass }}"
    update_password: on_create
    default_project: admin
- name: add placement to admin role
  os_user_role:
    user: placement
    role: admin
    project: service

- name: create the placement service
  os_keystone_service:
    state: present
    name: placement
    service_type: placement
    description: Placement API
- name: Create the placement  service API endpoints
  os_keystone_service_endpoint:
    state: present
    service: "placement"
    interface: "public"
    url: "http://controller:8778"
    region: "RegionOne"
- name: internal url
  os_keystone_service_endpoint:
    state: present
    service: "placement"
    interface: "internal"
    url: "http://controller:8778"
    region: "RegionOne"
- name: admin url
  os_keystone_service_endpoint:
    state: present
    service: "placement"
    interface: "admin"
    url: "http://controller:8778"
    region: "RegionOne"

