- name: install rabbitmq-server
  yum: name=rabbitmq-server state=latest
- name: start and enabled rabbitmq service
  service: name=rabbitmq-server.service state=started enabled=yes
- name: create rabbitmq user and give all permision
  rabbitmq_user:
    user: "{{ rabbitmq_user }}"
    password: "{{ rabbitmq_user_pass }}"
    permissions:
      - vhost: /
        configure_priv: .*
        read_priv: .*
        write_priv: .*
    state: present
