---
- name: Populate the Compute databases
#  shell: su -s /bin/sh -c "nova-manage api_db sync" nova;su -s /bin/sh -c "nova-manage db sync" nova;su -s /bin/sh -c "nova-manage cell_v2 map_cell0" nova;su -s /bin/sh -c "nova-manage cell_v2 create_cell --name=cell1 --verbose" nova;su -s /bin/sh -c "nova-manage db sync" nova;
  shell: su -s /bin/sh -c "nova-manage api_db sync" nova;su -s /bin/sh -c "nova-manage cell_v2 map_cell0" nova;su -s /bin/sh -c "nova-manage cell_v2 create_cell --name=cell1 --verbose" nova;su -s /bin/sh -c "nova-manage db sync" nova
- name: give /var/log/nova/nova-manage.log permision
  shell: chown nova:nova /var/log/nova/nova-manage.log
- name: restart nova-services with handlers
  service: "name={{ item }} state=restarted enabled=yes"
  with_items: 
    - openstack-nova-api.service
    - openstack-nova-consoleauth.service 
    - openstack-nova-scheduler.service
    - openstack-nova-conductor.service
    - openstack-nova-novncproxy.service
- name: restart openstack-nova-compute.service 
  service: "name={{ item }} state=restarted enabled=yes"
  with_items: [libvirtd.service,openstack-nova-compute.service]
