---
- include: controller/nova_database.yml
  when: inventory_hostname in groups['controller']
  tags: database
- include: controller/base.yml
  when: inventory_hostname in groups['controller']
- include: controller/main.yml
  when: inventory_hostname in groups['controller']
  tags: controller-nova-1
- include: compute/main.yml
  tags: compute-nova-1
  when: inventory_hostname in groups['compute']
- name: Discover compute hosts
  shell: su -s /bin/sh -c "nova-manage cell_v2 discover_hosts --verbose" nova
  when: inventory_hostname in groups['controller']
