---
## controller
- name: restart neutron-server
  service: 'name=neutron-server.service state=restarted enabled=yes'
- name: restart openstack-neutron-openvswitch.service
  service: 'name=neutron-openvswitch-agent.service state=restarted enabled=yes'
- name: estart neutron-dhcp-agent.service
  service: 'name=neutron-dhcp-agent.service state=restarted enabled=yes'
- name: restart neutron-l3-agent.service
  service: 'name=neutron-l3-agent.service state=restarted enabled=yes'
- name: restart neutron-metadata-agent.service
  service: 'name=neutron-metadata-agent.service state=restarted enabled=yes'
- name: restart openstack-nova-api.service
  service: 'name=openstack-nova-api.service state=restarted enabled=yes'

## compute
- name:  restart neutron-openvswitch-agent.service
  service: 'name=neutron-openvswitch-agent.service state=restarted enabled=yes' 
- name: restart openstack-nova-compute.service
  service: 'name=openstack-nova-compute.service state=restarted enabled=yes'
- name: restart neutron-dhcp-agent.service
  service: 'name=neutron-dhcp-agent.service state=restarted enabled=yes'
