- name:  yum install openstack-keystone httpd mod_wsgi
  yum: name={{ item }} state=latest
  with_items: [openstack-keystone,httpd,mod_wsgi]
- name: replace the httpd.conf
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: keystone
    group: keystone
  with_items:
    - src: httpd.conf.j2
      dest: /etc/httpd/conf/httpd.conf
    - src: keystone.conf.j2
      dest: /etc/keystone/keystone.conf
  notify: enable and restart httpd
- name: Populate the Identity service database
  shell: su -s /bin/sh -c "keystone-manage db_sync" keystone

#
- name: fernet_setup
  shell: keystone-manage fernet_setup --keystone-user keystone --keystone-group keystone
- name: Create the keystone fernet-keys  directories
  file:
    path: "{{ item.path }}"
    state: "directory"
    owner: "{{ item.owner|default('root') }}"
    group: "{{ item.group|default('root') }}"
    mode: "{{ item.mode|default('0754') }}"
    recurse: "{{ item.recurse|default('false') }}"
  with_items:
    - { path: "/etc/keystone/fernet-keys/", owner: "keystone", group: "keystone", mode: "0755" }
    - { path: "/etc/keystone/credential-keys/", owner: "keystone", group: "keystone", mode: "0755" }


- name: copy fernet-keys to keystone node
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "keystone"
    group: "keystone"
    mode: "0600"
  with_items:
    - src: 0
      dest: /etc/keystone/fernet-keys/
    - src: 1
      dest: /etc/keystone/fernet-keys/

- name: credential_setup
  shell: keystone-manage credential_setup --keystone-user keystone --keystone-group keystone

#
- name: copy credential-keys to keystone node
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "keystone"
    group: "keystone"
    mode: "0600"
  with_items:
    - src: 0
      dest: /etc/keystone/credential-keys/
    - src: 1
      dest: /etc/keystone/credential-keys/

#
- name: copy the tmp.sh and admin-openrc to all the node /root
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "keystone"
    group: "keystone"
    mode: "0655"
  with_items:
    - src: tmp.sh
      dest: /root
    - src: admin-openrc
      dest: /root

- name: decide the admin user is created
  shell: source /root/tmp.sh;openstack user list|grep admin
  register: admin_result
  ignore_errors: true
- name: Bootstrap the Identity service
  shell: keystone-manage bootstrap --bootstrap-password admin  --bootstrap-admin-url http://controller:35357/v3/  --bootstrap-internal-url http://controller:35357/v3/ --bootstrap-public-url http://controller:5000/v3/ --bootstrap-region-id RegionOne
  when: admin_result|failed
  notify: restart httpd
- name: restart httpd
  service: name=httpd state=restarted enabled=yes
- name: wait the httpd start
  pause: seconds=10

- name: Create a link to the /usr/share/keystone/wsgi-keystone.conf file
#  file: src=/usr/share/keystone/wsgi-keystone.conf dest=/etc/httpd/conf.d/ state=link 
  file: "src=/usr/share/keystone/wsgi-keystone.conf dest=/etc/httpd/conf.d/wsgi-keystone.conf state=link"
- name: restart httpd again
  service: name=httpd state=restarted enabled=yes
- name: wait the httpd start
  pause: seconds=20
